/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 当前平台是否支持受限执行（Windows 且模块加载成功） */
export declare function available(): boolean

export interface RunOptions {
  cwd: string
  timeoutMs: number
  env?: Record<string, string>
  processMemoryMb?: number
  jobMemoryMb?: number
  activeProcessLimit?: number
}

/** 以受限令牌 + Job Object 执行命令（异步，后台线程） */
export declare function runRestricted(command: string, opts: RunOptions): Promise<RunResult>

export interface RunResult {
  ok: boolean
  code: number
  stdout: string
  stderr: string
  timedOut: boolean
  /** full | reduced | basic | job-only | none */
  level: string
  error?: string
}
