/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 审计修复（H-2）：终止指定 run_id 的运行（Job terminate 杀整棵进程树）。
 * 返回 false = 该 run 已结束/未注册（幂等，无害）。
 */
export declare function abortRun(runId: number): boolean

/** 当前平台是否支持受限执行（Windows 且模块加载成功） */
export declare function available(): boolean

export interface RunOptions {
  cwd: string
  timeoutMs: number
  env?: Record<string, string>
  processMemoryMb?: number
  jobMemoryMb?: number
  activeProcessLimit?: number
  /**
   * 审计修复（H-2）：运行 ID——JS 侧传自增 id，abort_run(id) 可随时终止
   * 该次运行的整棵进程树（Job terminate；阻塞等待随之返回）
   */
  runId?: number
}

/** 以受限令牌 + Job Object 执行命令（异步，后台线程） */
export declare function runRestricted(command: string, opts: RunOptions): Promise<RunResult>

export interface RunResult {
  ok: boolean
  code: number
  stdout: string
  stderr: string
  timedOut: boolean
  /** full | reduced | basic | job-only | none */
  level: string
  error?: string
}
